# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/manuel/projects/CryptoPrinterEditor/mainUI.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from libs.UI_Additions import ChartPlotter, IndicatorOverviewLister, IndicatorSettingsLister

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1017, 655)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.chart_plotter = ChartPlotter(self.centralwidget)
        self.chart_plotter.setGeometry(QtCore.QRect(10, 60, 700, 531))
        self.chart_plotter.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.chart_plotter.setFrameShadow(QtWidgets.QFrame.Plain)
        self.chart_plotter.setLineWidth(1)
        self.chart_plotter.setObjectName("chart_plotter")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 1001, 42))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.plotsettings_layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.plotsettings_layout.setContentsMargins(0, 0, 0, 0)
        self.plotsettings_layout.setObjectName("plotsettings_layout")
        self.symbol_input = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.symbol_input.sizePolicy().hasHeightForWidth())
        self.symbol_input.setSizePolicy(sizePolicy)
        self.symbol_input.setMinimumSize(QtCore.QSize(100, 30))
        self.symbol_input.setAlignment(QtCore.Qt.AlignCenter)
        self.symbol_input.setObjectName("symbol_input")
        self.plotsettings_layout.addWidget(self.symbol_input)
        self.length_slider = QtWidgets.QSlider(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.length_slider.sizePolicy().hasHeightForWidth())
        self.length_slider.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.length_slider.setFont(font)
        self.length_slider.setMinimum(10)
        self.length_slider.setMaximum(500)
        self.length_slider.setSingleStep(10)
        self.length_slider.setProperty("value", 200)
        self.length_slider.setTracking(True)
        self.length_slider.setOrientation(QtCore.Qt.Horizontal)
        self.length_slider.setInvertedAppearance(False)
        self.length_slider.setInvertedControls(False)
        self.length_slider.setObjectName("length_slider")
        self.plotsettings_layout.addWidget(self.length_slider)
        self.interval_comboBox = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.interval_comboBox.sizePolicy().hasHeightForWidth())
        self.interval_comboBox.setSizePolicy(sizePolicy)
        self.interval_comboBox.setMinimumSize(QtCore.QSize(100, 30))
        self.interval_comboBox.setObjectName("interval_comboBox")
        self.plotsettings_layout.addWidget(self.interval_comboBox)
        self.plot_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot_button.sizePolicy().hasHeightForWidth())
        self.plot_button.setSizePolicy(sizePolicy)
        self.plot_button.setMinimumSize(QtCore.QSize(100, 30))
        self.plot_button.setObjectName("plot_button")
        self.plotsettings_layout.addWidget(self.plot_button)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(720, 60, 290, 530))
        self.stackedWidget.setObjectName("stackedWidget")
        self.indicatoroverview_page = QtWidgets.QWidget()
        self.indicatoroverview_page.setObjectName("indicatoroverview_page")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.indicatoroverview_page)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 291, 531))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.indicatorsettings_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.indicatorsettings_layout.setContentsMargins(0, 0, 0, 0)
        self.indicatorsettings_layout.setObjectName("indicatorsettings_layout")
        self.addIndicator_layout = QtWidgets.QHBoxLayout()
        self.addIndicator_layout.setObjectName("addIndicator_layout")
        self.indicators_combobox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.indicators_combobox.sizePolicy().hasHeightForWidth())
        self.indicators_combobox.setSizePolicy(sizePolicy)
        self.indicators_combobox.setMaximumSize(QtCore.QSize(16777215, 40))
        self.indicators_combobox.setObjectName("indicators_combobox")
        self.addIndicator_layout.addWidget(self.indicators_combobox)
        self.addIndicator_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addIndicator_button.sizePolicy().hasHeightForWidth())
        self.addIndicator_button.setSizePolicy(sizePolicy)
        self.addIndicator_button.setMaximumSize(QtCore.QSize(50, 40))
        self.addIndicator_button.setObjectName("addIndicator_button")
        self.addIndicator_layout.addWidget(self.addIndicator_button)
        self.indicatorsettings_layout.addLayout(self.addIndicator_layout)
        self.indicatoroverview_view = IndicatorOverviewLister(self.verticalLayoutWidget)
        self.indicatoroverview_view.setObjectName("indicatoroverview_view")
        self.indicatorsettings_layout.addWidget(self.indicatoroverview_view)
        self.stackedWidget.addWidget(self.indicatoroverview_page)
        self.indicatorsettings_page = QtWidgets.QWidget()
        self.indicatorsettings_page.setObjectName("indicatorsettings_page")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.indicatorsettings_page)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(-1, -1, 291, 531))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.indicatorsettings_view = IndicatorSettingsLister(self.verticalLayoutWidget_2)
        self.indicatorsettings_view.setObjectName("indicatorsettings_view")
        self.verticalLayout.addWidget(self.indicatorsettings_view)
        self.saveindicator_button = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveindicator_button.sizePolicy().hasHeightForWidth())
        self.saveindicator_button.setSizePolicy(sizePolicy)
        self.saveindicator_button.setMinimumSize(QtCore.QSize(0, 40))
        self.saveindicator_button.setObjectName("saveindicator_button")
        self.verticalLayout.addWidget(self.saveindicator_button)
        self.stackedWidget.addWidget(self.indicatorsettings_page)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(9, 599, 1001, 51))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.save_layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.save_layout.setContentsMargins(0, 0, 0, 0)
        self.save_layout.setObjectName("save_layout")
        self.path_input = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.path_input.sizePolicy().hasHeightForWidth())
        self.path_input.setSizePolicy(sizePolicy)
        self.path_input.setMaximumSize(QtCore.QSize(16777215, 40))
        self.path_input.setObjectName("path_input")
        self.save_layout.addWidget(self.path_input)
        self.save_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_button.sizePolicy().hasHeightForWidth())
        self.save_button.setSizePolicy(sizePolicy)
        self.save_button.setMaximumSize(QtCore.QSize(16777215, 40))
        self.save_button.setObjectName("save_button")
        self.save_layout.addWidget(self.save_button)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CryptoPrinter"))
        self.symbol_input.setText(_translate("MainWindow", "BTC/USDT"))
        self.plot_button.setText(_translate("MainWindow", "Plot"))
        self.addIndicator_button.setText(_translate("MainWindow", "+"))
        self.saveindicator_button.setText(_translate("MainWindow", "Save Indicator"))
        self.save_button.setText(_translate("MainWindow", "PushButton"))

